// <auto-generated />
using System;
using Caikon.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Caikon.Migrations
{
    [DbContext(typeof(CaikonContext))]
    [Migration("20210604215854_Second")]
    partial class Second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Caikon.Models.Login", b =>
                {
                    b.Property<int>("LoginUID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Acesso");

                    b.Property<string>("Senha");

                    b.Property<DateTime>("Validade");

                    b.HasKey("LoginUID");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("Caikon.Models.Pessoa", b =>
                {
                    b.Property<int>("PessoaUID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Cep");

                    b.Property<string>("Cpf");

                    b.Property<DateTime>("DataNascimento");

                    b.Property<string>("Email");

                    b.Property<string>("Nome");

                    b.HasKey("PessoaUID");

                    b.ToTable("Pessoa");
                });
#pragma warning restore 612, 618
        }
    }
}
